version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    description: テスト実行
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test

  deploy-docs:
    description: ドキュメントデプロイ
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - add_ssh_keys:
          fingerprints:
            - '31:fc:90:6d:c8:4f:24:44:2c:1b:c9:8a:bb:bc:53:b0'
      - run:
          command: |
            git config --global user.name 'Circle CI'
            git config --global user.email '<>'
            yarn deploy-docs

workflows:
  run-test:
    jobs:
      # テスト実行
      - test

      # ドキュメントデプロイ
      - deploy-docs:
          filters:
            branches:
              only:
                - /feature\/docs\/.*/
