version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    description: テスト実行
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test

  # NOTE: CircleCIで上手くいかなかった
  # https://github.com/zakzakst/make-library-practice/pull/29
  # deploy-docs:
  #   description: ドキュメントデプロイ
  #   docker:
  #     - image: cimg/node:18.14.2
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: yarn
  #     - add_ssh_keys:
  #         fingerprints:
  #           - 'xxxxx'
  #     - run:
  #         command: |
  #           git config --global user.name 'Circle CI'
  #           git config --global user.email '<>'
  #           yarn deploy-docs

workflows:
  run-test:
    jobs:
      # テスト実行
      - test

      # # ドキュメントデプロイ
      # - deploy-docs:
      #     filters:
      #       branches:
      #         only:
      #           - /feature\/docs\/.*/
